
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rihards
  password: rihards


development:
  <<: *default
  database: fasthunt_website_development
  username: rihards
  password: rihards


test:
  <<: *default
  database: fasthunt_website_test



production:
  <<: *default
  database: fasthunt_website_production
  username: fasthunt_website
  password: <%= ENV["FASTHUNT_WEBSITE_DATABASE_PASSWORD"] %>
